import Header from "@components/header";
import "./globals.css";
import MyApp from "./app";

export const metadata = {
  title: "Liga ROOT CE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body>
        <Header />
        <div className='container-root'>
          <MyApp>
            {children}
          </MyApp>
        </div>
      </body>
    </html>
  );
}
